agents:
  - id: mnist_agent01
    data:
      - dataset: MNIST
        labels: [0, 1]  
  - id: mnist_agent23
    data:
      - dataset: MNIST
        labels: [2, 3]
  - id: mnist_agent45
    data:
      - dataset: MNIST
        labels: [4, 5]
  - id: mnist_agent67
    data:
      - dataset: MNIST
        labels: [6, 7]
  - id: mnist_agent89
    data:
      - dataset: MNIST
        labels: [8, 9]
  - id: fashion_agent01
    data:
      - dataset: FashionMNIST
        labels: [0, 1]
  - id: fashion_agent23
    data:
      - dataset: FashionMNIST
        labels: [2, 3]
  - id: fashion_agent45
    data:
      - dataset: FashionMNIST
        labels: [4, 5]
  - id: fashion_agent67
    data:
      - dataset: FashionMNIST
        labels: [6, 7]
  - id: fashion_agent89
    data:
      - dataset: FashionMNIST
        labels: [8, 9]
batch_size: 128
num_workers: 0
run_name: multi_agent_moe_2_datasets
algorithm: multi_agent_moe
max_steps: 2000
gpus: 1
inner_steps: 4
accelerator: cpu
graph_type: complete
fiedler_value: 0.7
num_labels: 20 # This should be the total number of labels across all datasets
lr_start: 0.005
lr_finish: 0.0005
rho: 0.5